# Generated by Django 4.1.6 on 2023-02-19 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
